---
site_name: "WEBSITE name"
site_description: "This website is awesome."
site_copyright: "CC BY-NC-ND 4.0"
author: "Unnamed Author"
author_email: "author@email.com"
canonical_uri: "http://your-site-uri/"
#base_uri: "blog/"

feed_format: "atom"
disqus: "no"

site_language: "en"
encoding: "utf-8"
locale: "en_US.UTF-8"

max_entries: 10
default_category: "Miscellaneous"

datefmt_long: "%c"
datefmt_short: "%d-%b-%Y"
datefmt_mini: "%F"

extra_dirs: ['media']
...

